# Generated by Django 4.2.4 on 2023-08-31 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("ordered_by", models.CharField(max_length=200)),
                ("shipping_address", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subtotal", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Order Received", "Order Received"),
                            ("Order Processing", "Order Processing"),
                            ("On the way", "On the way"),
                            ("Order Completed", "Order Completed"),
                            ("Order Canceled", "Order Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash On Delivery", "Cash On Delivery"),
                            ("Khalti", "Khalti"),
                        ],
                        default="Cash On Delivery",
                        max_length=20,
                    ),
                ),
                (
                    "payment_completed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="store.cart"
                    ),
                ),
            ],
        ),
    ]
