# Generated by Django 4.2.4 on 2023-09-02 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.PositiveIntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.PositiveIntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="admins")),
                ("mobile", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
