# Generated by Django 4.2.4 on 2023-09-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_order_discount_alter_order_subtotal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Dog", "Dog"), ("Cat", "Cat")], default="Dog", max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
