# Generated by Django 4.2.4 on 2023-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_category_delete_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AddField(
            model_name="product",
            name="direction_to_use",
            field=models.TextField(default="No direction_to_use provided"),
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(default="No ingredients listed"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="Standard size", max_length=100),
        ),
    ]
