# Generated by Django 4.2.4 on 2023-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_description_product_direction_to_use_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("Pens", "Pens"),
                    ("Beds", "Beds"),
                    ("Crates", "Crates"),
                    ("Gates", "Gates"),
                    ("Cameras", "Cameras"),
                    ("Treats", "Treats"),
                    ("Food", "Food"),
                    ("Bowls & Feeders", "Bowls & Feeders"),
                    ("Food Storage & Accessories", "Food Storage & Accessories"),
                    ("Toys", "Toys"),
                    ("Collar & Leashes", "Collar & Leashes"),
                ],
                default="Pens",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Khalti", "Khalti")], default="Khalti", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="direction_to_use",
            field=models.TextField(default="No direction to use provided"),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default="Small",
                max_length=10,
            ),
        ),
    ]
