# Generated by Django 4.2.4 on 2023-09-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_remove_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="VetDoctor",
        ),
    ]
