# Generated by Django 4.2.4 on 2023-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_rating_user_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery",
            field=models.TextField(default="No description available"),
        ),
    ]
