# Generated by Django 4.2.4 on 2023-09-17 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0028_alter_rating_user_alter_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="product",
            name="direction_to_use",
        ),
        migrations.RemoveField(
            model_name="product",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer_details",
            field=models.TextField(default="No manufacturer details"),
        ),
        migrations.AddField(
            model_name="product",
            name="return_exchange_policy",
            field=models.TextField(default="No return exchange polocy"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("Beds & Mats", "Beds & Mats"),
                    ("Healthcare", "Healthcare"),
                    ("Treats & Chews", "Treats & Chews"),
                    ("Food", "Food"),
                    ("Bowls & Feeders", "Bowls & Feeders"),
                    ("Toys", "Toys"),
                    ("Collar & Leashes", "Collar & Leashes"),
                    ("Training Aids", "Training Aids"),
                    ("Grooming Supplies", "Grooming Supplies"),
                    ("Crates & Carriers", "Crates & Carriers"),
                ],
                default="Food",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
