# Generated by Django 4.2.4 on 2023-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_remove_product_delivery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufacturer_details",
        ),
        migrations.RemoveField(
            model_name="product",
            name="return_exchange_policy",
        ),
        migrations.AddField(
            model_name="product",
            name="direction_to_use",
            field=models.TextField(default="No direction to use provided"),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(default="No ingredients listed"),
        ),
    ]
