# Generated by Django 4.2.4 on 2023-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_remove_product_manufacturer_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Pedigree", "Pedigree"),
                    ("Whiskas", "Whiskas"),
                    ("Royal Canin", "Royal Canin"),
                    ("Drools", "Drools"),
                    ("Farmina", "Farmina"),
                    ("Sheba", "Sheba"),
                    ("Brunos Wild", "Brunos Wild"),
                    ("Catsan", "Catsan"),
                ],
                default="Sheba",
                max_length=20,
            ),
        ),
    ]
