# Generated by Django 4.2.4 on 2023-09-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0031_remove_product_size_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("D - Beds & Mats", "D - Beds & Mats"),
                    ("D - Healthcare", "D - Healthcare"),
                    ("D - Treats & Chews", "D - Treats & Chews"),
                    ("D - Food", "D - Food"),
                    ("D - Bowls & Feeders", "D - Bowls & Feeders"),
                    ("D - Toys", "D - Toys"),
                    ("D - Collar & Leashes", "D - Collar & Leashes"),
                    ("D - Training Aids", "D - Training Aids"),
                    ("D - Grooming Supplies", "D - Grooming Supplies"),
                    ("D - Crates & Carriers", "D - Crates & Carriers"),
                    ("C - Food", "C - Food"),
                    ("C - Grooming", "C - Grooming"),
                    ("C - Toys", "C - Toys"),
                    ("C - Treats", "C - Treats"),
                    ("C - Transport", "C - Transport"),
                    ("C - Bedding", "C - Bedding"),
                    ("C - Collors & Harness", "C - Collors & Harness"),
                    ("C - Training Aids", "C - Training Aids"),
                    ("C - Bowls", "C - Bowls"),
                    ("C - Kernels", "C - Kernels"),
                ],
                default="Food",
                max_length=30,
            ),
        ),
    ]
