# Generated by Django 4.2.4 on 2023-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0034_customer_order_products_order_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="store.cartitem"),
        ),
    ]
