# Generated by Django 4.2.4 on 2023-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0037_salesrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
