# Generated by Django 4.2.5 on 2023-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0039_alter_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="cost_based_on_quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
