# Generated by Django 4.2.5 on 2023-10-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0040_salesrecord_cost_based_on_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="individual_product_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
