# Generated by Django 4.2.3 on 2023-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catguide',
            table='catguide_model',
        ),
    ]
