# Generated by Django 4.2.3 on 2023-08-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogguide', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetGuide',
            new_name='DogGuide',
        ),
        migrations.AlterModelTable(
            name='dogguide',
            table='dogguide_guidemodel',
        ),
    ]
