# Generated by Django 4.2.3 on 2023-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogguide', '0002_rename_petguide_dogguide_alter_dogguide_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dogguide',
            table='dogguide_model',
        ),
    ]
