"""
<<<<<<< HEAD
Django settings for pawsome project.

Generated by 'django-admin startproject' using Django 4.2.3.
=======
Django settings for dj_shop project.

Generated by 'django-admin startproject' using Django 4.2.4.
>>>>>>> bb75f3e (login and home page)

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = "django-insecure-b8)x@fbr@w1cz$puqr%r2ftkm&w=zy-=)-!8m_9rg4dv+bac3t"
=======
SECRET_KEY = "django-insecure-*7r)@&gb^@jp=ygr)y#m2@etr%sbaa146y#=8l2r*^4te3=ww!"
>>>>>>> bb75f3e (login and home page)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
<<<<<<< HEAD
    'crispy_forms',
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'products.apps.ProductsConfig',
=======
    "django.contrib.contenttypes",
    'crispy_forms',
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'store',
>>>>>>> bb75f3e (login and home page)
    'register.apps.RegisterConfig',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pawsome.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
<<<<<<< HEAD
                "django.template.context_processors.media",
=======
>>>>>>> bb75f3e (login and home page)
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pawsome.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pawsome',
        'USER': 'postgres',
        'PASSWORD': 'ocacine10',
        'HOST': 'localhost',
        'PORT': '5433'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

<<<<<<< HEAD
MEDIA_URL = "media/"
=======
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'pawsome/static/'),
        os.path.join(BASE_DIR, 'media/'),
]


MEDIA_URL = "image/"
>>>>>>> bb75f3e (login and home page)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

<<<<<<< HEAD
# STATIC_ROOT = os.path.join(BASE_DIR, 'pawsome/static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'pawsome/static/'),
        os.path.join(BASE_DIR, 'media/'),
]

=======
>>>>>>> bb75f3e (login and home page)
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

<<<<<<< HEAD
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
=======
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
>>>>>>> bb75f3e (login and home page)
