# Generated by Django 4.2.4 on 2023-08-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.IntegerField()),
                ("product_price", models.IntegerField()),
                ("pet_type", models.CharField(max_length=20)),
                ("pet_brand", models.CharField(max_length=20)),
                ("pet_picture", models.ImageField(upload_to="")),
            ],
        ),
    ]
