# Generated by Django 4.2.4 on 2023-08-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="product_name",
            field=models.CharField(),
        ),
    ]
