# Generated by Django 4.2.4 on 2023-08-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productmodel_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="pet_brand",
            new_name="product_brand",
        ),
    ]
