# Generated by Django 4.2.4 on 2023-08-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_pet_picture_productmodel_product_picture_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductModel",
            new_name="Product",
        ),
    ]
